// <auto-generated />
// EnumCodeGenerator로 자동 생성된 파일입니다. 수동 편집 금지.

namespace Jinhyeong_GeneratedEnums
{
    public enum ESkillTriggerType
    {
        None,
        OnTick,
        OnAttack,
        OnOreBreak
    }

    public enum ESkillNodeType
    {
        None,
        Sequence,
        Selector,
        Parallel,
        Inverter,
        Cooldown,
        Chance,
        TriggerOnTick,
        TriggerOnAttack,
        TriggerOnOreBreak,
        TargetSelf,
        TargetNearest,
        TargetFarthest,
        TargetRandom,
        TargetAll,
        TargetNearestForward,
        TargetCone,
        HitSingle,
        HitArea,
        HitBeam,
        HitChain,
        HitDeathBurst,
        DespawnAfterTime,
        DespawnAfterHits,
        DespawnAfterBounces,
        DespawnOnWall,
        LaunchInstant,
        LaunchStraight,
        LaunchArc,
        LaunchCurve,
        BuffSelf,
        DebuffOnHit
    }

    public enum ESkillParamKey
    {
        None,
        Cooldown,
        Chance,
        Threshold,
        Range,
        Index,
        HalfAngle,
        Angle,
        Absolute,
        Damage,
        Radius,
        Length,
        Width,
        DamageInterval,
        MaxPerTarget,
        Value,
        Speed,
        MaxDistance,
        Duration,
        ArcHeight,
        MaxBounces,
        Visual,
        RequireAll,
        ModifierKey,
        BuffId,
        DebuffId
    }

    public enum EBuffType
    {
        None,
        DamageBoost,
        AttackSpeedBoost,
        HealOverTime,
        Shield
    }

    public enum EDebuffType
    {
        None,
        DamageOverTime,
        SlowReduce,
        DamageReceiveIncrease,
        Stun
    }
}
