// <auto-generated />
// EnumCodeGenerator로 자동 생성된 파일입니다. 수동 편집 금지.
// (현재는 _Enum.json 캐시 기준으로 만들어둔 임시 파일 — 다음 sync 시 덮어써짐)

namespace Jinhyeong_GeneratedEnums
{
    public enum ESkillTriggerType
    {
        None,
        OnTick,
        OnAttack,
        OnOreBreak
    }

    public enum ESkillNodeType
    {
        None,
        Sequence,
        Selector,
        Parallel,
        Inverter,
        Cooldown,
        Chance,
        OnTickTrigger,
        OnAttackTrigger,
        OnOreBreakTrigger,
        SelfTargeting,
        AreaNearTargeting,
        AreaFarTargeting,
        AreaRandomTargeting,
        ScreenAllTargeting,
        NearestDirectionTargeting,
        RayTargeting,
        SingleHit,
        AoEHit,
        BeamHit,
        ChainLightningHit,
        DeathChainHit,
        DurationDespawn,
        OnHitDespawn,
        OnBounceLimitDespawn,
        OnWallHitDespawn,
        InstantLaunch,
        StraightLaunch,
        ParabolicLaunch,
        CurveLaunch,
        ApplyBuffSelf,
        ApplyDebuffOnHit
    }

    public enum ESkillParamKey
    {
        None,
        Cooldown,
        Chance,
        Threshold,
        Range,
        Index,
        HalfAngle,
        Angle,
        Absolute,
        Damage,
        Radius,
        Length,
        Width,
        DamageInterval,
        MaxPerTarget,
        Value,
        Speed,
        MaxDistance,
        Duration,
        ArcHeight,
        MaxBounces,
        Visual,
        RequireAll,
        ModifierKey,
        BuffId,
        DebuffId
    }

    public enum EBuffType
    {
        None,
        DamageBoost,
        AttackSpeedBoost,
        HealOverTime,
        Shield
    }

    public enum EDebuffType
    {
        None,
        DamageOverTime,
        SlowReduce,
        DamageReceiveIncrease,
        Stun
    }
}
