using System.Collections.Generic;
using System.IO;
using System.Text;

namespace Jinhyeong_GoogleSheetDataLoader.Editor
{
    public class EnumDef
    {
        public string Name;
        public List<string> Values;
    }

    public static class EnumCodeGenerator
    {
        public const string OutputFolder = "Assets/Scripts/GeneratedEnums";
        public const string EnumNamespace = "Jinhyeong_GeneratedEnums";
        public const string DefaultFileName = "GameEnum.cs";

        public static List<EnumDef> CollectFromRows(List<List<string>> rows)
        {
            var defs = new List<EnumDef>();
            if (rows == null || rows.Count == 0)
            {
                return defs;
            }

            List<string> header = rows[0];
            int columnCount = header.Count;

            for (int c = 0; c < columnCount; c++)
            {
                string rawName = header[c] != null ? header[c].Trim() : string.Empty;
                if (string.IsNullOrEmpty(rawName))
                {
                    continue;
                }
                if (rawName.StartsWith("#"))
                {
                    continue;
                }

                string enumName = SanitizeIdentifier(rawName);
                List<string> values = CollectValues(rows, c);
                if (values.Count == 0)
                {
                    continue;
                }

                defs.Add(new EnumDef { Name = enumName, Values = values });
            }

            return defs;
        }

        public static string WriteCombinedFile(IEnumerable<EnumDef> defs, string fileName)
        {
            EnsureFolder();

            var deduped = new List<EnumDef>();
            var seenNames = new HashSet<string>();
            foreach (EnumDef def in defs)
            {
                if (def == null || string.IsNullOrEmpty(def.Name))
                {
                    continue;
                }
                if (seenNames.Add(def.Name) == false)
                {
                    UnityEngine.Debug.LogWarning($"[EnumCodeGenerator] enum '{def.Name}' 이름이 여러 시트에서 중복되어 첫 번째만 사용됩니다");
                    continue;
                }
                deduped.Add(def);
            }

            string safeFileName = SanitizeFileName(string.IsNullOrEmpty(fileName) ? DefaultFileName : fileName);
            string path = Path.Combine(OutputFolder, safeFileName).Replace('\\', '/');

            if (deduped.Count == 0)
            {
                if (File.Exists(path))
                {
                    File.Delete(path);
                    string metaPath = path + ".meta";
                    if (File.Exists(metaPath))
                    {
                        File.Delete(metaPath);
                    }
                }
                return null;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// EnumCodeGenerator로 자동 생성된 파일입니다. 수동 편집 금지.");
            sb.AppendLine();
            sb.AppendLine("namespace " + EnumNamespace);
            sb.AppendLine("{");
            for (int i = 0; i < deduped.Count; i++)
            {
                EnumDef def = deduped[i];
                sb.AppendLine("    public enum " + def.Name);
                sb.AppendLine("    {");
                for (int v = 0; v < def.Values.Count; v++)
                {
                    sb.Append("        ").Append(def.Values[v]);
                    if (v < def.Values.Count - 1)
                    {
                        sb.Append(",");
                    }
                    sb.AppendLine();
                }
                sb.AppendLine("    }");
                if (i < deduped.Count - 1)
                {
                    sb.AppendLine();
                }
            }
            sb.AppendLine("}");

            File.WriteAllText(path, sb.ToString());
            return path;
        }

        private static List<string> CollectValues(List<List<string>> rows, int col)
        {
            var values = new List<string>();
            var seen = new HashSet<string>();
            for (int r = 1; r < rows.Count; r++)
            {
                List<string> row = rows[r];
                if (row == null || col >= row.Count)
                {
                    continue;
                }
                string raw = row[col] != null ? row[col].Trim() : string.Empty;
                if (string.IsNullOrEmpty(raw))
                {
                    continue;
                }
                if (raw.StartsWith("#"))
                {
                    continue;
                }
                string sanitized = SanitizeIdentifier(raw);
                if (seen.Add(sanitized) == false)
                {
                    continue;
                }
                values.Add(sanitized);
            }
            return values;
        }

        private static string SanitizeIdentifier(string raw)
        {
            if (string.IsNullOrEmpty(raw))
            {
                return "_";
            }
            var sb = new StringBuilder(raw.Length);
            for (int i = 0; i < raw.Length; i++)
            {
                char c = raw[i];
                bool valid = (c >= 'a' && c <= 'z')
                             || (c >= 'A' && c <= 'Z')
                             || (c >= '0' && c <= '9')
                             || c == '_';
                if (valid)
                {
                    sb.Append(c);
                    continue;
                }
                sb.Append('_');
            }
            if (sb.Length > 0 && sb[0] >= '0' && sb[0] <= '9')
            {
                sb.Insert(0, '_');
            }
            return sb.ToString();
        }

        private static string SanitizeFileName(string raw)
        {
            char[] invalid = Path.GetInvalidFileNameChars();
            var sb = new StringBuilder(raw.Length);
            for (int i = 0; i < raw.Length; i++)
            {
                char c = raw[i];
                if (System.Array.IndexOf(invalid, c) >= 0)
                {
                    sb.Append('_');
                    continue;
                }
                sb.Append(c);
            }
            string result = sb.ToString();
            if (result.EndsWith(".cs") == false)
            {
                result += ".cs";
            }
            return result;
        }

        private static void EnsureFolder()
        {
            if (Directory.Exists(OutputFolder) == false)
            {
                Directory.CreateDirectory(OutputFolder);
            }
        }
    }
}
